// @ts-nocheck
/**
 * Regression coverage — backlog 5b69402d-a2a9-4ccf-b623-2f844b0dc82e
 * "Agent extension READMEs render a literal '> >-' instead of the description"
 *
 * BUG-014 defect 2 (fixed at 3cafff6d) was that parseFrontmatter()'s scalar()
 * regex captured the YAML block-scalar INDICATOR TOKEN (e.g. `>-`) instead of
 * the folded body beneath a `description: >-` frontmatter field. That fix
 * repaired parseFrontmatter()'s output (covered by
 * migrate-agents.bug014.test.ts) and, transitively, manifest()'s
 * `extension.json` output — but nothing ever asserted the SAME fix reaches
 * readme()'s blockquote line, and readme() was not even exported for testing.
 *
 * This is not a hypothetical gap: `extensions/agents/{doc-cartographer,
 * doc-consumer,doc-evangelist,doc-reviewer}/README.md` were generated by the
 * PRE-FIX script at commit 9248e799 and still carry the literal `> >-` line
 * today (git main, and feat/agent-ir before this fix), because:
 *   - d2d22364 hand-patched only the 14 `extension.json` files, never the
 *     READMEs (`git show d2d22364 --stat` touches zero README.md).
 *   - 3cafff6d fixed the generator itself but explicitly rewrote no
 *     committed output ("No committed extension.json was rewritten" —
 *     and it likewise never touched any README.md).
 *   - The P4 README validator (scripts/validate-manifests.ts, rule (d)) only
 *     checks README.md length > 100 chars and rejects lorem-ipsum stubs; a
 *     4-char `> >-` line inside an otherwise-long file passes it silently.
 *
 * This test exercises readme() directly (now exported) fed a description
 * extracted by the (fixed) parseFrontmatter() from a live `description: >-`
 * block-scalar source, and asserts the emitted blockquote line is the real
 * folded text, never the bare indicator.
 *
 * To see it go RED: comment out the `blockHit` branch in parseFrontmatter's
 * scalar() (migrate-agents.mjs, ~line 251-256) so `rest` — the raw `>-` — is
 * returned as the description instead of being parsed as a block scalar.
 */
import { describe, expect, it } from 'vitest';
import { parseFrontmatter, readme } from '../migrate-agents.mjs';

describe('BL 5b69402d — readme() must never emit a bare YAML block-scalar indicator', () => {
  it('folds a `description: >-` block scalar into the README blockquote line (doc-cartographer live shape)', () => {
    const content = `---
description: >-
  FACTS subagent for the documentation trio. Given a scope (a directory with a
  manifest), it classifies the scope type, recalls the best-in-class doc
  frameworks from memory.
mode: subagent
model: deepseek/deepseek-flash
---
body
`;
    const { meta } = parseFrontmatter(content);
    const md = readme('doc-cartographer', meta.description, '/some/path.md', 'opencode');
    const line3 = md.split('\n')[2];

    // The exact defect shape from the live bug: the blockquote line was
    // literally "> >-" (or any bare block-scalar indicator).
    expect(line3).not.toBe('> >-');
    expect(line3).not.toMatch(/^> [|>][+-]?$/);
    expect(line3).toBe(
      '> FACTS subagent for the documentation trio. Given a scope (a directory with a ' +
        'manifest), it classifies the scope type, recalls the best-in-class doc ' +
        'frameworks from memory.',
    );
  });

  it('falls back to the "<id> agent" placeholder (not a bare indicator) when description is entirely absent', () => {
    const md = readme('some-agent', undefined, '/some/path.md', 'claude');
    const line3 = md.split('\n')[2];
    expect(line3).toBe('> some-agent agent');
    expect(line3).not.toMatch(/^> [|>][+-]?$/);
  });
});
