// @adhd/sox-task-queue — core types (SPEC §2-5)

// ─── TaskStatus ─────────────────────────────────────────────────────────────

export enum TaskStatus {
  Queued = 'queued',
  Running = 'running',
  Completed = 'completed',
  Failed = 'failed', // retries exhausted -> dead
  Cancelled = 'cancelled',
  Scheduled = 'scheduled', // waiting for scheduled_at to arrive
}

// ─── Task ────────────────────────────────────────────────────────────────────

export interface Task<T = unknown> {
  id: string; // UUIDv4, generated by enqueue if omitted
  type: string; // Logical task type for routing (e.g. 'reembed', 'email-send')
  status: TaskStatus;
  priority: number; // Higher = more urgent. Default: 0. Range: -128 to 127.
  payload: T; // Application-specific data. Must be JSON-serializable.
  retryCount: number; // Current retry attempt (0 = first execution)
  maxRetries: number; // 0 = no retries. Default: 3.
  scheduledAt: string | null; // ISO 8601. null = execute immediately on dequeue.
  created_at: string; // ISO 8601. Set at enqueue time.
  started_at: string | null; // ISO 8601. Set when a worker claims the task.
  completed_at: string | null; // ISO 8601. Set on complete or fail (terminal).
  error: string | null; // Last error message. null on success.
  dead: boolean; // true when maxRetries exhausted. Terminal.
  clientRequestId: string | null; // Idempotency key for dedup enqueue (see §7).
  result: string | null; // JSON-serialized result from the handler.
  leaseExpiresAt: string | null; // ISO 8601. Deadline for the current lease.
  workerId: string | null; // ID of the worker currently holding the lease.
  ttlMs: number | null; // Max wall-clock time before the task auto-fails.
}

// ─── TaskQueueConfig ─────────────────────────────────────────────────────────

export interface TaskQueueConfig {
  /** Path to the SQLite database file. ':memory:' is valid for testing. */
  dbPath: string;

  /** Maximum tasks to return in a single dequeue batch. Default: 10. */
  dequeueBatchSize?: number;

  /** Default maxRetries for tasks that don't specify one. Default: 3. */
  defaultMaxRetries?: number;

  /**
   * Heartbeat lease duration in milliseconds. The worker must heartbeat
   * within this window or the task is re-queued. Default: 30_000 (30s).
   */
  heartbeatTimeoutMs?: number;

  /**
   * Maximum wall-clock time before a task auto-fails. Overrides task-level
   * ttlMs. null = no global limit. Default: null.
   */
  defaultTtlMs?: number | null;

  /**
   * Whether to enable automatic re-queue of expired leases. When false,
   * expired tasks remain in 'running' state until manually resolved.
   * Default: true.
   */
  autoRequeueExpired?: boolean;

  /** Interval in milliseconds for the lease expiry reaper tick. Default: 5_000 (5s). */
  reaperIntervalMs?: number;

  /**
   * Maximum queue depth (count of queued+scheduled+running tasks) before
   * `enqueue`/`enqueueBatch` throw `QueueFullError`. 0 = unbounded.
   * Default: 0.
   *
   * Spec reconciliation: §2 omits this field from the `TaskQueueConfig`
   * code block, but D-8 in the decisions log names it explicitly
   * ("Optional per-queue maxDepth via config ... default: 0 = unbounded")
   * and §3's `enqueue` doc comment throws `QueueFullError` "if configured".
   * Added here so that documented behaviour is reachable.
   */
  maxQueueDepth?: number;

  /**
   * Called synchronously when a task transitions to dead (maxRetries
   * exhausted, via `fail()` or reaper lease-expiry). Must not throw --
   * errors are caught and logged at `warn` level.
   *
   * Spec reconciliation: named as a deferred spec-gap item in §13.5
   * ("Dead task alerting"). Implemented here as documented there.
   */
  onDead?: (task: Task) => void;
}

// ─── TaskFilter ──────────────────────────────────────────────────────────────

export interface TaskFilter {
  status?: TaskStatus | TaskStatus[];
  type?: string | string[];
  priorityMin?: number;
  priorityMax?: number;
  dead?: boolean;
  createdAfter?: string;
  createdBefore?: string;
  scheduledBefore?: string; // only tasks with scheduled_at <= this
  limit?: number;
  offset?: number;
  orderBy?: 'created_at' | 'priority' | 'scheduled_at';
  orderDir?: 'asc' | 'desc';
}

// ─── QueueStats ──────────────────────────────────────────────────────────────

export interface QueueStats {
  byStatus: Record<TaskStatus, number>;
  total: number;
  deadCount: number;
  runningCount: number;
  avgProcessingLatencyMs: number; // rolling average of completed - started
  retryDistribution: Record<number, number>; // retryCount -> count of live tasks
  oldestQueuedAgeMs: number; // age of the oldest 'queued' task
  heartbeatMisses: number; // count of tasks re-queued due to expired lease
  enqueueCount: number; // lifetime enqueues for this instance
  dequeueCount: number; // lifetime dequeues for this instance
  completeCount: number; // lifetime completions for this instance
  failCount: number; // lifetime terminal failures for this instance
}

// ─── EnqueueResult ───────────────────────────────────────────────────────────

export interface EnqueueResult {
  id: string;
  deduplicated: boolean; // true if this task was rejected as duplicate
  isNew: boolean; // true if this is a fresh enqueue
}

// ─── DequeueResult ───────────────────────────────────────────────────────────

export interface DequeueResult {
  task: Task;
  // The worker must call complete/fail/heartbeat before the lease expires.
  // The lease is automatically extended on heartbeat.
}

// ─── TaskQueue — primary interface (SPEC §3) ─────────────────────────────────

export interface TaskQueue {
  // ── Lifecycle ───────────────────────────────────────────────────────────

  /** Open the database, apply schema, start the lease expiry reaper. Idempotent. */
  open(): Promise<void>;

  /**
   * Graceful shutdown: wait for in-flight tasks to complete (up to
   * drainTimeoutMs), then stop the reaper and close the database.
   * THROWS TaskTimeoutError if tasks are still running after drainTimeoutMs.
   */
  close(opts?: { drainTimeoutMs?: number }): Promise<void>;

  /** Returns true between open() and close(). */
  readonly isOpen: boolean;

  // ── Enqueue ──────────────────────────────────────────────────────────────

  enqueue(task: Partial<Task> & { type: string; payload: unknown }): Promise<EnqueueResult>;

  enqueueBatch(
    tasks: Array<Partial<Task> & { type: string; payload: unknown }>,
  ): Promise<EnqueueResult[]>;

  // ── Dequeue ──────────────────────────────────────────────────────────────

  dequeue(workerId: string): Promise<DequeueResult[]>;

  // ── Completion ───────────────────────────────────────────────────────────

  complete(taskId: string, result?: unknown): Promise<void>;

  fail(taskId: string, error: string): Promise<void>;

  // ── Heartbeat ────────────────────────────────────────────────────────────

  heartbeat(taskId: string): Promise<boolean>;

  // ── Cancellation ─────────────────────────────────────────────────────────

  cancel(taskId: string): Promise<boolean>;

  isCancelled(taskId: string): Promise<boolean>;

  // ── Query ────────────────────────────────────────────────────────────────

  get(taskId: string): Promise<Task | null>;

  listTasks(filter?: TaskFilter): Promise<Task[]>;

  stats(): Promise<QueueStats>;

  countTasks(filter?: TaskFilter): Promise<number>;

  // ── Admin / Maintenance ──────────────────────────────────────────────────

  purgeCompleted(olderThanMs: number): Promise<number>;

  requeue(taskId: string): Promise<void>;

  deleteTasks(filter: TaskFilter): Promise<number>;
}

// ─── Worker pool (SPEC §4) ───────────────────────────────────────────────────

export interface WorkerPoolConfig {
  queue: TaskQueue;

  handler: (task: Task) => Promise<void>;

  /** Maximum number of concurrent task executions. Default: 1. */
  concurrency?: number;

  /** Poll interval in milliseconds when no tasks are available. Default: 1_000 (1s). */
  pollIntervalMs?: number;

  /**
   * Heartbeat interval in milliseconds. Default: heartbeatTimeoutMs / 3.
   *
   * Spec reconciliation: the pool only has access to `queue` through the
   * `TaskQueue` interface, which does not expose `heartbeatTimeoutMs`. The
   * default here is 10_000ms (i.e. the queue's own 30_000ms default / 3).
   * If you configure a non-default `heartbeatTimeoutMs` on the queue, set
   * this explicitly to `heartbeatTimeoutMs / 3` to match.
   */
  heartbeatIntervalMs?: number;

  /** Maximum time in ms to wait for running handlers during graceful shutdown. Default: 30_000. */
  drainTimeoutMs?: number;

  /** Name for this worker pool instance (used as workerId in lease). Default: auto UUID. */
  workerName?: string;

  /** If true, the pool starts polling immediately. Default: true. */
  autoStart?: boolean;
}

export interface WorkerPool {
  start(): void;

  stop(): Promise<void>;

  readonly isRunning: boolean;

  readonly activeCount: number;

  readonly stats: {
    tasksProcessed: number;
    tasksFailed: number;
    tasksTimedOut: number;
  };
}

// ─── Scheduler (SPEC §5) ─────────────────────────────────────────────────────

export interface SchedulerConfig {
  queue: TaskQueue;

  /** Default task type for scheduled tasks. Default: 'scheduled'. */
  defaultType?: string;

  /** Default priority for scheduled tasks. Default: 0. */
  defaultPriority?: number;

  /** Default maxRetries for scheduled tasks. Default: 0 (no retries for cron tasks). */
  defaultMaxRetries?: number;

  /** Poll interval in ms for checking due cron expressions. Default: 1_000 (1s). */
  tickIntervalMs?: number;

  /** Auto-start the tick loop. Default: true. */
  autoStart?: boolean;

  /**
   * Path to the SQLite database file backing `scheduler_entries`.
   *
   * Spec reconciliation: §5's `SchedulerConfig` code block does not list a
   * `dbPath`, yet `Scheduler.open()`'s doc comment says "Open the scheduler
   * database" and §6 defines `scheduler_entries` in the same DDL block as
   * `tasks`. If omitted, the scheduler reuses the `dbPath` of the
   * `SqliteTaskQueue` passed as `queue` (read via its `dbPath` property) —
   * both open independent WAL-mode connections to the same file, which is
   * the exact pattern WAL was chosen for (see SPEC D-1).
   */
  dbPath?: string;
}

export interface ScheduledEntry {
  id: string; // UUIDv4, auto-generated
  name: string; // Human-readable label. Must be unique.
  taskType: string; // Task type for the enqueued task.
  payload: unknown; // Payload for the enqueued task. Must be JSON-serializable.
  cronExpression: string; // Standard cron syntax. Backend: croner.

  priority?: number;
  maxRetries?: number;
  ttlMs?: number | null;

  /**
   * If true, on scheduler start, the first enqueue immediately fires (even
   * if the cron would not have fired yet). Default: false.
   */
  runOnStart?: boolean;

  /** Whether this entry is active. Inactive entries are skipped on tick. Default: true. */
  enabled: boolean;

  created_at: string;
  updated_at: string;
  lastEnqueuedAt: string | null;
  lastError: string | null;
}

export interface Scheduler {
  open(): Promise<void>;

  close(): Promise<void>;

  register(
    entry: Omit<ScheduledEntry, 'id' | 'created_at' | 'updated_at' | 'lastEnqueuedAt' | 'lastError'>,
  ): Promise<ScheduledEntry>;

  update(id: string, entry: Partial<ScheduledEntry>): Promise<ScheduledEntry>;

  unregister(id: string): Promise<void>;

  enable(id: string, enabled: boolean): Promise<void>;

  get(id: string): Promise<ScheduledEntry | null>;

  list(): Promise<ScheduledEntry[]>;

  triggerNow(id: string): Promise<string>;

  readonly isRunning: boolean;
  readonly nextTickAt: string | null;
}
