/**
 * libs/install-engine/src/ownership.ts — ADR-0004 §D5/§D6 ownership index.
 *
 * THE complete, machine-local record of EVERY filesystem location and config key an
 * install owns, keyed by (extId, scope). Enforces the governing invariants:
 *
 *   [inv:no-untracked-injection] — nothing soxe places (config key, file/dir, array
 *     value, materialized store, lockfile key, install-registry record) exists without
 *     a corresponding ownership entry, recorded at apply time from the capability's own
 *     return value.
 *   [inv:reversible-injection] — uninstall consumes this index and surgically reverses
 *     EXACTLY what was placed, leaving host files byte-clean of sox-owned content while
 *     preserving foreign entries.
 *
 * File: <dataRoot>/ownership.json (per scope, ADR-0004 §D2). Absolute paths on purpose
 * (machine-local cleanup truth — deliberately NOT portable, unlike the project ledger).
 *
 * Leaf-ish module: node builtins + the ledger types only. The actual reversal of
 * config-key/array-value entries is delegated to the ledger-reversal path in
 * lifecycle.ts (which has the deny-wins array logic); this module owns the
 * file/dir/store removal and the index bookkeeping.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { ownershipPathFor, type DataScope } from './data-paths.js';

// ─── Entry shapes ──────────────────────────────────────────────────────────────

/** One owned thing. `kind` selects how uninstall reverses it. */
export type OwnedEntry =
  | { kind: 'file-drop'; path: string }
  | { kind: 'materialize'; path: string }
  | { kind: 'config-key'; file: string; keyPath: string; appliedHash?: string }
  | { kind: 'array-values'; file: string; keyPath: string; values: string[] }
  | { kind: 'object-array-values'; file: string; keyPath: string; entries: Array<Record<string, unknown>>; identityField: string; identityValue: string }
  | { kind: 'lockfile-key'; file: string; keyPath: string }
  | { kind: 'registry-record'; extId: string; scope: string; root: string }
  // Slice 2 (service-lifecycle spec §9.4 / [inv:reversible-injection]): an OS unit
  // (launchd LaunchAgent / systemd --user) generated by `soxe service enable`.
  // uninstall/disable reverses it by unloading the unit then deleting the file.
  // `appliedHash` is the content-address of the rendered unit (§9.3) so `doctor`
  // can detect an artifact-stale unit. `supervisor` selects the unload mechanism.
  | { kind: 'os-unit'; label: string; unitPath: string; supervisor: 'launchd' | 'systemd'; appliedHash: string };

/** Everything one install (extId, scope) owns. */
export interface OwnershipRecord {
  extId: string;
  scope: string;
  /** Owning host (claude/codex) — informational; entries carry their own targets. */
  host?: string;
  /** Bundle this extension was installed as part of, if any (ADR-0004 store grouping). */
  bundleId?: string;
  /** Content address of the placed artifact (ADR-0003), when known. */
  artifactChecksum?: string;
  installedAt: string;
  updatedAt: string;
  entries: OwnedEntry[];
}

export interface OwnershipFile {
  version: 1;
  owned: OwnershipRecord[];
}

// ─── Typed ownership errors (BL-620 — the ownership write is the commit point) ──

/**
 * The ownership index at `filePath` is unparseable / structurally invalid.
 * In a STRICT load this must THROW (never read as empty — an empty read is
 * silently wiped by the next save, which is exactly how the doctor-tick entry
 * was lost). Non-strict loads (the legacy default) still return empty.
 */
export class OwnershipCorruptError extends Error {
  readonly filePath: string;
  constructor(filePath: string, detail?: string) {
    super(
      `[ownership] corrupt ownership file at ${filePath}` +
      (detail !== undefined ? `: ${detail}` : '') +
      ` — refusing to read it as empty (that would silently wipe every entry on the next save)`,
    );
    this.name = 'OwnershipCorruptError';
    this.filePath = filePath;
  }
}

/**
 * The ownership file changed on disk between load and save — an external writer
 * (another process / another agent) wrote it out from under us. Saving now would
 * silently drop their update. Refuse rather than perform a lost update.
 */
export class OwnershipConflictError extends Error {
  readonly filePath: string;
  constructor(filePath: string) {
    super(
      `[ownership] ownership file changed on disk since it was loaded (external change detected): ${filePath} ` +
      `— refusing to overwrite a concurrent update (no silent lost update)`,
    );
    this.name = 'OwnershipConflictError';
    this.filePath = filePath;
  }
}

// ─── Read / write (atomic) ──────────────────────────────────────────────────────

export function readOwnership(filePath: string, opts: { strict?: boolean } = {}): OwnershipFile {
  if (!fs.existsSync(filePath)) return { version: 1, owned: [] };
  try {
    const parsed = JSON.parse(fs.readFileSync(filePath, 'utf8')) as OwnershipFile;
    if (!Array.isArray(parsed.owned)) {
      if (opts.strict) throw new OwnershipCorruptError(filePath, '`owned` is not an array');
      return { version: 1, owned: [] };
    }
    return parsed;
  } catch (e) {
    if (opts.strict) {
      if (e instanceof OwnershipCorruptError) throw e;
      throw new OwnershipCorruptError(filePath, e instanceof Error ? e.message : String(e));
    }
    return { version: 1, owned: [] };
  }
}

export function writeOwnershipAtomic(filePath: string, data: OwnershipFile): void {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const tmp = filePath + '.tmp';
  fs.writeFileSync(tmp, JSON.stringify(data, null, 2) + '\n', 'utf8');
  fs.renameSync(tmp, filePath);
}

// ─── Ownership index (per scope) ────────────────────────────────────────────────

/**
 * The ownership index for one scope. `dataDir` is the resolved `.adhd/sox-ecosystem`
 * directory; the index lives at `<dataDir>/ownership.json`. Callers obtain `dataDir`
 * from the data-paths resolver (dataRoot(scope, root)).
 */
export class OwnershipIndex {
  private readonly filePath: string;
  private data: OwnershipFile;
  /** Stat of the file at load time (null = absent), for optimistic-concurrency save. */
  private statAtLoad: { mtimeMs: number; size: number } | null;

  private constructor(
    filePath: string,
    data: OwnershipFile,
    statAtLoad: { mtimeMs: number; size: number } | null,
  ) {
    this.filePath = filePath;
    this.data = data;
    this.statAtLoad = statAtLoad;
  }

  /** Load (or create) the ownership index at an explicit ownership.json path. */
  static loadFromFile(filePath: string, opts: { strict?: boolean } = {}): OwnershipIndex {
    return new OwnershipIndex(
      filePath,
      readOwnership(filePath, opts.strict === true ? { strict: true } : {}),
      statFile(filePath),
    );
  }

  /** Load the ownership index for a scope via the data-paths resolver. */
  static load(scope: DataScope, root?: string, opts?: { strict?: boolean }): OwnershipIndex {
    return OwnershipIndex.loadFromFile(ownershipPathFor(scope, root), opts);
  }

  get path(): string {
    return this.filePath;
  }

  /** Return the record for (extId, scope), or undefined. */
  get(extId: string, scope: string): OwnershipRecord | undefined {
    return this.data.owned.find((r) => r.extId === extId && r.scope === scope);
  }

  /** Return a shallow copy of all records (for inspection/tests). */
  all(): OwnershipRecord[] {
    return [...this.data.owned];
  }

  /**
   * Record (upsert) the complete owned set for (extId, scope). Replaces any prior
   * record's `entries` with the new set (callers pass the full set produced by THIS
   * install). `installedAt` is preserved across updates; `updatedAt` is refreshed.
   * Enforces [inv:no-untracked-injection]: this is the single write path.
   */
  record(opts: {
    extId: string;
    scope: string;
    host?: string;
    bundleId?: string;
    artifactChecksum?: string;
    entries: OwnedEntry[];
  }): void {
    const now = new Date().toISOString();
    const idx = this.data.owned.findIndex(
      (r) => r.extId === opts.extId && r.scope === opts.scope,
    );
    if (idx === -1) {
      this.data.owned.push({
        extId: opts.extId,
        scope: opts.scope,
        ...(opts.host !== undefined ? { host: opts.host } : {}),
        ...(opts.bundleId !== undefined ? { bundleId: opts.bundleId } : {}),
        ...(opts.artifactChecksum !== undefined ? { artifactChecksum: opts.artifactChecksum } : {}),
        installedAt: now,
        updatedAt: now,
        entries: opts.entries,
      });
    } else {
      const prior = this.data.owned[idx]!;
      this.data.owned[idx] = {
        ...prior,
        ...(opts.host !== undefined ? { host: opts.host } : {}),
        ...(opts.bundleId !== undefined ? { bundleId: opts.bundleId } : {}),
        ...(opts.artifactChecksum !== undefined ? { artifactChecksum: opts.artifactChecksum } : {}),
        updatedAt: now,
        entries: opts.entries,
      };
    }
  }

  /**
   * PI-6 / BL-142: generate a stable uniqueness key for an OwnedEntry.
   * Must stay in sync with supersededEntries() below.
   */
  private static entryKey(e: OwnedEntry): string {
    switch (e.kind) {
      case 'file-drop':
      case 'materialize':
        return `${e.kind}:${e.path}`;
      case 'config-key':
      case 'array-values':
      case 'object-array-values':
        return `${e.kind}:${e.file}:${e.keyPath}`;
      case 'lockfile-key':
        return `${e.kind}:${e.file}:${e.keyPath}`;
      case 'registry-record':
        return `${e.kind}:${e.extId}:${e.scope}:${e.root}`;
      case 'os-unit':
        return `${e.kind}:${e.label}`;
    }
  }

  /**
   * Deduplicate an array of OwnedEntry by (kind, target). The LAST occurrence
   * of each key wins (callers which overwrite a previous entry with a newer
   * value expect the later one to survive).
   */
  static dedupeEntries(entries: OwnedEntry[]): OwnedEntry[] {
    const seen = new Set<string>();
    const result: OwnedEntry[] = [];
    // Iterate in reverse so the LAST occurrence of each key wins.
    for (let i = entries.length - 1; i >= 0; i--) {
      const e = entries[i]!;
      const key = OwnershipIndex.entryKey(e);
      if (!seen.has(key)) {
        seen.add(key);
        result.unshift(e);
      }
    }
    return result;
  }

  /**
   * PI-6 / BL-142: one-time compaction — deduplicate entries across ALL records
   * in this index, preserving the most recent occurrence of each (kind, target).
   */
  compact(): void {
    for (const rec of this.data.owned) {
      rec.entries = OwnershipIndex.dedupeEntries(rec.entries);
    }
  }

  /** Append entries to the existing record for (extId, scope) (creating it if absent). */
  addEntries(extId: string, scope: string, entries: OwnedEntry[], meta?: {
    host?: string; bundleId?: string; artifactChecksum?: string;
  }): void {
    const existing = this.get(extId, scope);
    // PI-6 / BL-142: deduplicate by (kind, target) before merging
    const uniqueNew = OwnershipIndex.dedupeEntries(entries);
    const merged = existing ? OwnershipIndex.dedupeEntries([...existing.entries, ...uniqueNew]) : uniqueNew;
    const host = meta?.host ?? existing?.host;
    const bundleId = meta?.bundleId ?? existing?.bundleId;
    const artifactChecksum = meta?.artifactChecksum ?? existing?.artifactChecksum;
    this.record({
      extId, scope, entries: merged,
      ...(host !== undefined ? { host } : {}),
      ...(bundleId !== undefined ? { bundleId } : {}),
      ...(artifactChecksum !== undefined ? { artifactChecksum } : {}),
    });
  }

  /** Remove the record for (extId, scope) entirely. */
  remove(extId: string, scope: string): void {
    this.data.owned = this.data.owned.filter(
      (r) => !(r.extId === extId && r.scope === scope),
    );
  }

  /**
   * Persist atomically. Optimistic-concurrency guarded (BL-620 / INV-4): before
   * the rename, re-stat the file and compare against the stat recorded at load.
   * If the file changed on disk since load (mtime or size), an external writer
   * updated it out from under us — throw OwnershipConflictError rather than
   * silently clobbering their update. After a successful write, re-record the
   * new stat so a subsequent save on this instance does not self-conflict.
   */
  save(): void {
    const current = statFile(this.filePath);
    const loaded = this.statAtLoad;
    const changed =
      (loaded === null) !== (current === null) ||
      (loaded !== null && current !== null &&
        (loaded.mtimeMs !== current.mtimeMs || loaded.size !== current.size));
    if (changed) throw new OwnershipConflictError(this.filePath);
    writeOwnershipAtomic(this.filePath, this.data);
    this.statAtLoad = statFile(this.filePath);
  }

  /**
   * BL-620 / INV-1+INV-2+INV-3: record an OS-unit ownership entry as the COMMIT
   * POINT of an os-unit mutation. Strict-loads (corrupt index ⇒ throw), upserts
   * the entry, saves (external change ⇒ throw), then RE-READS the file and
   * asserts the entry actually persisted — THROWS if any step fails. This is the
   * fail-loud replacement for the old `try { addEntries; save } catch (silent)`
   * pattern that let a failed write leave a unit orphaned forever.
   */
  static upsertOsUnitEntry(
    filePath: string,
    opts: {
      extId: string;
      scope: string;
      label: string;
      unitPath: string;
      supervisor: 'launchd' | 'systemd';
      appliedHash: string;
    },
  ): void {
    const idx = OwnershipIndex.loadFromFile(filePath, { strict: true });
    idx.addEntries(opts.extId, opts.scope, [{
      kind: 'os-unit',
      label: opts.label,
      unitPath: opts.unitPath,
      supervisor: opts.supervisor,
      appliedHash: opts.appliedHash,
    }]);
    idx.save();
    const verify = readOwnership(filePath, { strict: true });
    const rec = verify.owned.find((r) => r.extId === opts.extId && r.scope === opts.scope);
    const entry = rec?.entries.find(
      (e) => e.kind === 'os-unit' && e.label === opts.label,
    );
    if (entry === undefined || entry.kind !== 'os-unit' || entry.appliedHash !== opts.appliedHash) {
      throw new Error(
        `[ownership] os-unit entry '${opts.label}' was not persisted to ${filePath} ` +
        `— the ownership write is the commit point; refusing to report success`,
      );
    }
  }

  /**
   * BL-620 / INV-1+INV-3: remove the OS-unit ownership entry for `label` from
   * (extId, scope), strict-loading and verifying the removal persisted. Returns
   * `false` on an idempotent no-op (record absent or entry already gone) so a
   * `remove-tick`/`disable` of a never-recorded unit is not an error. THROWS on
   * corrupt load, concurrent external change, or a save that does not persist.
   */
  static removeOsUnitEntry(
    filePath: string,
    opts: { extId: string; scope: string; label: string },
  ): boolean {
    const idx = OwnershipIndex.loadFromFile(filePath, { strict: true });
    const rec = idx.get(opts.extId, opts.scope);
    if (rec === undefined) return false;
    const had = rec.entries.some((e) => e.kind === 'os-unit' && e.label === opts.label);
    if (!had) return false;
    rec.entries = rec.entries.filter(
      (e) => !(e.kind === 'os-unit' && e.label === opts.label),
    );
    idx.save();
    const verify = readOwnership(filePath, { strict: true });
    const vRec = verify.owned.find((r) => r.extId === opts.extId && r.scope === opts.scope);
    if (vRec?.entries.some((e) => e.kind === 'os-unit' && e.label === opts.label)) {
      throw new Error(
        `[ownership] os-unit entry '${opts.label}' still present after remove+save at ${filePath}`,
      );
    }
    return true;
  }
}

/** Stat a file (or null if absent) for the optimistic-concurrency save guard. */
function statFile(filePath: string): { mtimeMs: number; size: number } | null {
  try {
    const st = fs.statSync(filePath);
    return { mtimeMs: st.mtimeMs, size: st.size };
  } catch {
    return null;
  }
}

// ─── Diff helper for update/upgrade (ADR-0004 §D6) ──────────────────────────────

/**
 * Compute the set of owned entries present in `oldEntries` but NOT in `newEntries`
 * — the SUPERSEDED entries an update must remove before placing the new artifact
 * (e.g. a renamed skill dir, a relocated store). Identity is by kind + target.
 */
export function supersededEntries(
  oldEntries: OwnedEntry[],
  newEntries: OwnedEntry[],
): OwnedEntry[] {
  const key = (e: OwnedEntry): string => {
    switch (e.kind) {
      case 'file-drop':
      case 'materialize':
        return `${e.kind}:${e.path}`;
      case 'config-key':
      case 'array-values':
      case 'object-array-values':
        return `${e.kind}:${e.file}:${e.keyPath}`;
      case 'lockfile-key':
        return `${e.kind}:${e.file}:${e.keyPath}`;
      case 'registry-record':
        return `${e.kind}:${e.extId}:${e.scope}:${e.root}`;
      case 'os-unit':
        return `${e.kind}:${e.label}`;
    }
  };
  const newKeys = new Set(newEntries.map(key));
  return oldEntries.filter((e) => !newKeys.has(key(e)));
}
