#!/usr/bin/env node
/**
 * build-routing-index.ts — Agent decision-routing index builder
 *
 * Walks the nx project graph + each package's sox.{area,group,concerns,invariants,entrypoints}
 * metadata and emits generated routing files. NEVER hand-maintain the outputs — the drift
 * gate is the whole point. Modeled on the BL-33 build-index / check-registry-sync
 * byte-mirror pattern.
 *
 * Outputs (all in outDir, default docs/routing/):
 *   outDir/map.json        — machine-readable, every tagged project with concerns/invariants
 *   outDir/INDEX.md        — human-readable root project listing
 *   outDir/<area>/INDEX.md — per-area human-readable listing (also copied to libs/<area>/INDEX.md)
 */

import * as child_process from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';

interface SoxMetadata {
  area: string;
  group: string;
  concerns: string[];
  invariants: string[];
  entrypoints: string[];
}

interface ProjectEntry {
  name: string;
  path: string;
  pkgName?: string | undefined;
  description?: string | undefined;
  concerns: string[];
  invariants: string[];
  entrypoints: string[];
  tags: string[];
}

interface MapJson {
  generated: string;
  schema: string;
  projects: Record<string, Record<string, Record<string, ProjectEntry>>>;
}

function execJson(cmd: string, cwd: string): unknown {
  const result = child_process.execSync(cmd, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
  return JSON.parse(result);
}

function getProjectNames(root: string): string[] {
  const result = execJson('npx nx show projects --json', root) as string[];
  return result;
}

function getProjectInfo(root: string, projectName: string): { root: string; tags: string[]; pkgName?: string | undefined; description?: string | undefined } {
  const info = execJson(`npx nx show project "${projectName}" --json`, root) as {
    root: string;
    tags: string[];
    metadata?: { description?: string; js?: { packageName?: string } };
  };
  return {
    root: info.root,
    tags: info.tags ?? [],
    pkgName: info.metadata?.js?.packageName,
    description: info.metadata?.description,
  };
}

function readSoxMetadata(projectRoot: string, workspaceRoot: string): SoxMetadata | undefined {
  const pkgPath = path.join(workspaceRoot, projectRoot, 'package.json');
  if (!fs.existsSync(pkgPath)) return undefined;
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8')) as { sox?: SoxMetadata };
    return pkg.sox;
  } catch {
    return undefined;
  }
}

function buildProjectEntries(root: string): ProjectEntry[] {
  const names = getProjectNames(root);
  const entries: ProjectEntry[] = [];

  for (const name of names) {
    const info = getProjectInfo(root, name);
    const sox = readSoxMetadata(info.root, root);
    if (!sox) continue;

    entries.push({
      name,
      path: info.root,
      pkgName: info.pkgName,
      description: info.description,
      concerns: sox.concerns ?? [],
      invariants: sox.invariants ?? [],
      entrypoints: sox.entrypoints ?? [],
      tags: info.tags,
    });
  }

  return entries;
}

function groupByArea(entries: ProjectEntry[]): Record<string, Record<string, Record<string, ProjectEntry>>> {
  const areas: Record<string, Record<string, Record<string, ProjectEntry>>> = {};

  for (const entry of entries) {
    const areaTag = entry.tags.find(t => t.startsWith('area:'));
    if (!areaTag) continue;
    const area = areaTag.replace('area:', '');
    const groupTag = entry.tags.find(t => t.startsWith('group:'));
    const group = groupTag ? groupTag.replace('group:', '') : '_ungrouped';

    if (!areas[area]) areas[area] = {};
    if (!areas[area][group]) areas[area][group] = {};
    areas[area][group][entry.name] = entry;
  }

  return areas;
}

function mdEscape(s: string): string {
  return s.replace(/\|/g, '\\|');
}

function emitMapJson(outDir: string, entries: ProjectEntry[]): string {
  const grouped = groupByArea(entries);
  const map: MapJson = {
    generated: '<auto>',
    schema: 'docs/routing/map.json — generated by scripts/build-routing-index.ts, never hand-edit',
    projects: grouped,
  };

  fs.mkdirSync(outDir, { recursive: true });
  const filePath = path.join(outDir, 'map.json');
  fs.writeFileSync(filePath, JSON.stringify(map, null, 2) + '\n', 'utf8');
  return filePath;
}

function emitRootIndex(outDir: string, entries: ProjectEntry[]): string {
  const grouped = groupByArea(entries);
  const lines: string[] = [];

  lines.push('# Routing Index');
  lines.push('');
  lines.push('> Generated by `scripts/build-routing-index.ts`. Never hand-edit.');
  lines.push('');
  lines.push('For intent→scope mapping, see [ROUTER.md](./ROUTER.md).');
  lines.push('');

  const sortedAreas = Object.keys(grouped).sort();

  for (const area of sortedAreas) {
    lines.push(`## Area: \`${area}\``);
    lines.push('');
    lines.push(`See [\`${area}/INDEX.md\`](${area}/INDEX.md) for area-level guidance.`);
    lines.push('');

    const groups = grouped[area];
    // Invariant: `area` was just drawn from Object.keys(grouped), so grouped[area]
    // is always present — noUncheckedIndexedAccess can't see that, hence the guard.
    if (!groups) continue;
    const sortedGroups = Object.keys(groups).sort();

    for (const group of sortedGroups) {
      const projects = groups[group];
      // Invariant: `group` was just drawn from Object.keys(groups); see above.
      if (!projects) continue;
      const sortedProjects = Object.keys(projects).sort();

      lines.push(`### Group: \`${group}\``);
      lines.push('');
      lines.push('| Package | Description |');
      lines.push('|---------|-------------|');

      for (const projName of sortedProjects) {
        const proj = projects[projName];
        // Invariant: `projName` was just drawn from Object.keys(projects); see above.
        if (!proj) continue;
        const desc = proj.description ? mdEscape(proj.description.slice(0, 120)) : '-';
        const pkgRef = proj.pkgName ? `\`${proj.pkgName}\`` : `\`${projName}\``;
        lines.push(`| ${pkgRef} | ${desc} |`);
      }

      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('## Projects without area tags');
  lines.push('');

  const untagged = entries.filter(e => !e.tags.some(t => t.startsWith('area:')));
  if (untagged.length > 0) {
    lines.push('| Name | Path | Concerns |');
    lines.push('|------|------|----------|');
    for (const proj of untagged.sort((a, b) => a.name.localeCompare(b.name))) {
      const concerns = proj.concerns.length > 0 ? proj.concerns.slice(0, 3).join(', ') + (proj.concerns.length > 3 ? '...' : '') : '-';
      lines.push(`| \`${proj.name}\` | \`${proj.path}\` | ${mdEscape(concerns)} |`);
    }
    lines.push('');
  } else {
    lines.push('*(none)*');
    lines.push('');
  }

  fs.mkdirSync(outDir, { recursive: true });
  const filePath = path.join(outDir, 'INDEX.md');
  fs.writeFileSync(filePath, lines.join('\n'), 'utf8');
  return filePath;
}

function emitAreaIndex(entries: ProjectEntry[], area: string, outDir: string): string {
  const grouped = groupByArea(entries);
  const groups = grouped[area];
  if (!groups) return '';

  const lines: string[] = [];

  lines.push(`# \`libs/${area}/\` — Area Index`);
  lines.push('');
  lines.push('> Generated by `scripts/build-routing-index.ts`. Never hand-edit.');
  lines.push('');
  lines.push(`For area-level guidance, see [\`libs/${area}/CLAUDE.md\`](../libs/${area}/CLAUDE.md).`);
  lines.push('');

  const sortedGroups = Object.keys(groups).sort();

  for (const group of sortedGroups) {
    const projects = groups[group];
    // Invariant: `group` was just drawn from Object.keys(groups); noUncheckedIndexedAccess
    // can't see that, hence the guard.
    if (!projects) continue;
    const sortedProjects = Object.keys(projects).sort();

    lines.push(`## Group: \`${group}\``);
    lines.push('');

    for (const projName of sortedProjects) {
      const proj = projects[projName];
      // Invariant: `projName` was just drawn from Object.keys(projects); see above.
      if (!proj) continue;
      const pkgRef = proj.pkgName ? `\`${proj.pkgName}\`` : `\`${projName}\``;

      lines.push(`### ${pkgRef}`);
      lines.push('');
      lines.push(`- **Path:** \`${proj.path}\``);
      if (proj.description) {
        lines.push(`- **Description:** ${proj.description}`);
      }
      lines.push('');

      if (proj.concerns.length > 0) {
        lines.push('**Concerns:**');
        for (const c of proj.concerns) {
          lines.push(`- ${c}`);
        }
        lines.push('');
      }

      if (proj.invariants.length > 0) {
        lines.push('**Invariants:**');
        for (const inv of proj.invariants) {
          lines.push(`- ${inv}`);
        }
        lines.push('');
      }

      lines.push(`**Build:** \`npx nx build ${projName}\``);
      lines.push(`**Test:** \`npx nx test ${projName}\``);
      lines.push('');
    }
  }

  const areaOutDir = path.join(outDir, area);
  fs.mkdirSync(areaOutDir, { recursive: true });
  const filePath = path.join(areaOutDir, 'INDEX.md');
  fs.writeFileSync(filePath, lines.join('\n'), 'utf8');
  return filePath;
}

function copyAreaIndexToLibs(root: string, outDir: string, area: string): void {
  const srcPath = path.join(outDir, area, 'INDEX.md');
  if (!fs.existsSync(srcPath)) return;

  const dstDir = path.join(root, 'libs', area);
  fs.mkdirSync(dstDir, { recursive: true });
  const dstPath = path.join(dstDir, 'INDEX.md');
  fs.copyFileSync(srcPath, dstPath);
}

export function buildRoutingIndex(opts: { root: string; outDir: string; libsRoot?: string | undefined }): string[] {
  const { root, outDir, libsRoot = root } = opts;
  const entries = buildProjectEntries(root);
  const files: string[] = [];

  files.push(emitMapJson(outDir, entries));
  files.push(emitRootIndex(outDir, entries));

  const grouped = groupByArea(entries);
  for (const area of Object.keys(grouped)) {
    const f = emitAreaIndex(entries, area, outDir);
    if (f) {
      files.push(f);
      // `libsRoot` defaults to `root` for real generation runs (routing:build-index),
      // preserving existing behaviour byte-for-byte. Dry-run callers that pass a
      // scratch `outDir` for comparison purposes (check-routing-drift.ts) MUST also
      // pass a scratch `libsRoot` — otherwise this copy mutates the real committed
      // `root/libs/<area>/INDEX.md` as a side effect of merely running the check,
      // which made that half of the drift gate tautological (see BL-257 report).
      copyAreaIndexToLibs(libsRoot, outDir, area);
      files.push(path.join(libsRoot, 'libs', area, 'INDEX.md'));
    }
  }

  const fileList = files.map(f => `  ${f}`).join('\n');
  console.log(`build-routing-index: done — ${entries.length} tagged projects, ${Object.keys(grouped).length} areas\n${fileList}`);
  return files;
}

// Only auto-run when this file is the process entry point (`npx tsx
// scripts/build-routing-index.ts`). Without this guard, importing
// `buildRoutingIndex` for its side effects (as check-routing-drift.ts does)
// ALSO re-ran this top-level block on import — using the importer's own
// process.argv, i.e. root=cwd/outDir=docs/routing by default — silently
// overwriting the real committed docs/routing/*.md, map.json, and
// libs/data/INDEX.md as an import side effect. That made the drift gate
// (check-routing-drift.ts) tautological: it clobbered the committed
// baseline with a fresh regen *before* diffing a temp regen against it,
// so it could never observe real drift. See BL-257 report.
if (import.meta.url === `file://${process.argv[1]}`) {
  const root = process.argv[2] ?? process.cwd();
  const outDir = process.argv[3] ?? path.join(root, 'docs', 'routing');
  buildRoutingIndex({ root, outDir });
}
