#!/usr/bin/env node
/**
 * plan-status.mjs — derive memory-program plan status from the live backlog graph.
 *
 * WHY THIS EXISTS
 * ---------------
 * `docs/reporting/memory/PLAN.md` and `STATE.md` are supposed to be the source of truth for
 * "what is left". Between 2026-07-31 and 2026-08-03 both drifted badly while looking authoritative:
 * PLAN.md named 39 BL ids that had already closed, and STATE.md carried a prominent warning
 * ("62% of the backlog appears nowhere in the plan") that was true when written and false by the
 * time anyone read it. An agent following either document would have worked on finished items.
 *
 * That is the same failure mode BL-224 fixed for BACKLOG.md's own status header (back when
 * BACKLOG.md existed — [ADR-0011] Stage 3 deleted it): a derived fact maintained by hand. The fix
 * is the same — derive it, and provide a --check mode so a stale document fails a guard instead of
 * quietly misleading the next reader. The source of that derivation is now the backlog graph
 * (queried via the `backlog` CLI), not a markdown file.
 *
 * A packet's status is defined ENTIRELY by the backlog status of the BL ids it targets:
 *
 *   DONE     every target id is closed (graph status RESOLVED/DONE/etc — see the open-set below)
 *   PARTIAL  some targets closed, some still open
 *   OPEN     no target is closed
 *
 * This is deliberate and follows BL-225: a packet is done when its *backlog items* are verifiably
 * done, not when someone believes the code landed. Several packets (PKT-47, 48, 51, 53) have code
 * merged and still read OPEN here — correctly, because their acceptance was never fully met.
 * If you think a packet is done, close its BL item with a red->green test; do not edit this output.
 *
 * USAGE
 *   node tools/plan-status.mjs              # rewrite the derived blocks in PLAN.md and STATE.md
 *   node tools/plan-status.mjs --check      # exit 1 on genuine drift, exit 2 if the backlog store
 *                                           # could not be reached (never exit 0 in either case)
 *   node tools/plan-status.mjs --check --advisory
 *                                           # same checks, but ALWAYS exit 0 — warns loudly to
 *                                           # stderr instead of failing. This is what pre-commit
 *                                           # runs (DEBT-HOOK-PLANSTATUS-GATES-EVERY-COMMIT-001):
 *                                           # a normal source-code commit must never be blocked by
 *                                           # the availability, size, or freshness of the backlog
 *                                           # store, an external mutable service. The BLOCKING form
 *                                           # (`--check` with no `--advisory`) still runs — for a
 *                                           # human/agent verifying deliberately, and as a targeted
 *                                           # pre-commit gate specifically when PLAN.md/STATE.md
 *                                           # themselves are staged (see .husky/pre-commit).
 *   node tools/plan-status.mjs --json       # emit the computed model, write nothing
 *
 * EXIT CODES for --check (advisory or not, --advisory just downgrades all of the below to 0):
 *   0  everything matches the graph, no stale prose
 *   1  genuine drift — a derived block is stale, or an audited claim names finished work
 *   2  the backlog store could not be reached/read (CLI missing, non-zero exit, malformed JSON,
 *      or the query timed out) — DISTINCT from 1 on purpose: this is an infra fault, not drift,
 *      and callers (the pre-commit hook, a human, CI) must be able to tell the two apart instead
 *      of treating "the store is down" as "the docs are wrong" (they were indistinguishable
 *      before DEBT-HOOK-PLANSTATUS-GATES-EVERY-COMMIT-001, and that made a corrupted store a
 *      repo-wide commit stoppage that read as a docs failure).
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PLAN = resolve(ROOT, 'docs/reporting/memory/PLAN.md');
const STATE = resolve(ROOT, 'docs/reporting/memory/STATE.md');

// [ADR-0011 Stage 3] the backlog graph is queried via the `backlog` CLI — the same first-class,
// stable command surface every sibling script in tools/ already shells out to for graph state
// (check-bl-id-integrity.mjs, backlog-stats.mjs). Overridable for tests, same pattern
// tools/test-bl446-arg-validation.mjs already establishes for allocate-bl-id.mjs.
const BACKLOG_BIN = process.env.PLAN_STATUS_BACKLOG_BIN || 'backlog';
const PAGE = 200;

const BEGIN = '<!-- PLAN-STATUS:BEGIN -->';
const END = '<!-- PLAN-STATUS:END -->';
const GENERATED_NOTE =
  '<!-- Generated by tools/plan-status.mjs from the backlog graph. Do not hand-edit — run the tool. -->';

/**
 * BL-435 — the audited-prose marker.
 *
 * All rewriting and checking above is bounded by BEGIN/END, so a hand-written section sits outside
 * the guard entirely. That is not hypothetical: STATE.md's "What to do next" led a session at two
 * DONE packets (PKT-41/BL-391, PKT-19/BL-329), and PLAN.md's "Wave summary" read "Total: 56 packets"
 * against a derived ledger of 72 with two whole waves missing — both while `--check` printed OK.
 *
 * Scanning ALL prose for closed ids does not work, and this was measured rather than assumed:
 * STATE.md's prose references 58 BL ids of which 46 are closed, nearly all of them legitimate
 * history ("BL-361 shipped"). A guard that fires 46 times is a guard that gets deleted.
 *
 * So an audited region is opted in with AUDIT_MARKER, and inside it only ACTIONABLE claims are
 * checked. The two known-bad sections share a shape that makes "actionable" mechanical:
 *   - editorial/historical narrative lives in `>` blockquotes (including the ⚠️ notes that recount
 *     the original incident by naming its DONE ids — those must not fire);
 *   - the declared target of a to-do item is its **bold** title (`**PKT-30 (BL-328)**`), while
 *     incidental citations sit in the unbolded tail (`(BL-367's lesson)`).
 * Measured on the live "What to do next": 3 ids reach the scan, 0 false positives, and the original
 * incident is caught.
 */
const AUDIT_MARKER = '<!-- PLAN-STATUS:AUDIT -->';

/**
 * Sections that MUST carry AUDIT_MARKER. Without this, deleting the marker silences the guard —
 * which is the recurrence hole the whole item is about. Keyed by file label, matched on heading
 * prefix so editorial wording after the em dash can change freely.
 */
const REQUIRED_AUDITED_SECTIONS = {
  'PLAN.md': ['## Wave summary'],
  'STATE.md': ['## What to do next'],
};

/**
 * Items that are open in the backlog graph but deliberately outside this program's scope. Without this
 * list every unrelated repo defect (dispatch-optimizer, packaging, plan hygiene) shows up as an
 * unscheduled coverage gap, which is how the previous "62% uncovered" figure became alarming
 * noise rather than a signal. Keep this list short and justify each entry in PLAN.md's
 * "Explicitly OUT OF SCOPE" section — an id belongs here only if it is genuinely a different
 * project, never merely because it is inconvenient.
 */
const OUT_OF_SCOPE = new Set([
  // "Dispatch-optimizer / plan hygiene"
  99, 103, 104, 105, 228, 258, 261, 296, 298,
  // "Packaging, native ABI, bundling"
  282, 284, 285, 288, 291, 292, 305, 306, 308, 314, 333, 355, 408,
  // "Bundler / CI packaging"
  307, 309,
  // "Product surface"
  315,
  // "Open, but deliberately NO packet"
  225, 163, 283, 411,
]);

/**
 * DEBT-HOOK-PLANSTATUS-GATES-EVERY-COMMIT-001 — a dedicated error type for "the store could not be
 * reached/read", distinct from every other Error this module throws (a genuinely stale derived
 * block, a bad AUDIT_MARKER, etc). Before this, an unreachable store and real drift both surfaced
 * as an undifferentiated non-zero exit — a corrupted store read exactly like a stale doc, and three
 * commits were lost before anyone read the stack trace to tell them apart. `main()` catches this
 * type specifically to print a distinct message and (in `--advisory` mode) exit 0 instead of
 * blocking a commit that has nothing to do with the backlog.
 */
export class StoreUnavailableError extends Error {
  constructor(message) {
    super(message);
    this.name = 'StoreUnavailableError';
  }
}

// Bounds how long a single `backlog list-items` call may run. Pre-commit must never hang
// indefinitely on a slow/wedged store — a timeout turns "hangs forever" into "fails loudly and
// fast", which readGraphStatuses reports as StoreUnavailableError like any other unreachable-store
// case. Generous enough not to false-positive on a warm store under normal load (measured well
// under 1s locally), tight enough that a wedged store cannot stall a commit.
const GRAPH_QUERY_TIMEOUT_MS = 10_000;

/**
 * [ADR-0011 Stage 3 / D2] Query the live backlog graph via the `backlog` CLI, paginated — 417 known
 * live `BL`-family items already exceeds a naive default page size, and future growth must never
 * silently truncate. `excludeArchived: false` is required: staleRefs (below) needs closed ids too,
 * so the query must return the full family, not just currently-open items.
 *
 * [D3] A CLI failure (binary missing, non-zero exit, malformed JSON) must be LOUD, never swallowed
 * into an empty Map — an empty Map would make every id read as absent-therefore-closed, the single
 * worst failure mode this script can produce (a false "everything is done").
 */
export const readGraphStatuses = () => {
  const statuses = new Map();
  let offset = 0;
  for (;;) {
    let out;
    try {
      out = execFileSync(
        BACKLOG_BIN,
        [
          'query',
          '--input',
          JSON.stringify({
            view: 'list',
            filter: { repo: 'sox-ecosystem', family: 'BL', excludeArchived: false, status: 'all' },
            limit: PAGE,
            offset,
          }),
        ],
        {
          encoding: 'utf8',
          stdio: ['ignore', 'pipe', 'ignore'],
          // execFileSync's default maxBuffer is 1 MB. The sox-ecosystem item
          // list crossed that this session (measured 1,801,669 bytes on ONE
          // line), so stdout was TRUNCATED MID-JSON and JSON.parse threw
          // "Unexpected end of JSON input". Because plan-status runs in the
          // pre-commit hook, that silently blocked commits REPO-WIDE — and the
          // failure looked like a backlog-store problem rather than a buffer
          // limit, which is the worst possible misdirection.
          //
          // This is a growth-triggered failure: it worked until the graph got
          // big enough. Sized well above the current list so it does not
          // re-trigger on the next few thousand items; the paging below (PAGE)
          // bounds it further.
          maxBuffer: 64 * 1024 * 1024,
          // DEBT-HOOK-PLANSTATUS-GATES-EVERY-COMMIT-001: bound the call so a wedged/slow store
          // cannot hang a commit indefinitely. execFileSync sends SIGTERM and sets err.killed/
          // err.signal on the resulting error, not err.code — distinguished explicitly below.
          timeout: GRAPH_QUERY_TIMEOUT_MS,
        },
      );
    } catch (err) {
      const timedOut = err.killed === true || err.signal != null;
      throw new StoreUnavailableError(
        timedOut
          ? `plan-status: \`${BACKLOG_BIN} query\` (offset=${offset}) did not return within ${GRAPH_QUERY_TIMEOUT_MS}ms and was killed (signal=${err.signal}). ` +
            `The backlog store is likely slow/wedged rather than reachable. Try \`backlog version\` by hand.`
          : `plan-status: \`${BACKLOG_BIN} query\` failed (offset=${offset}) — ${err.status !== undefined ? `exit ${err.status}` : err.message}. ` +
            `Is the backlog CLI installed and the store reachable? Try \`backlog version\` / \`backlog query --input '{"view":"list"}' \` by hand. ` +
            `(plan-status refuses to silently treat this as "zero items" — that would report every backlog id as done.)`,
      );
    }
    let parsed;
    try {
      parsed = JSON.parse(out);
    } catch (err) {
      throw new StoreUnavailableError(`plan-status: \`${BACKLOG_BIN} query\` returned non-JSON output — ${err.message}`);
    }
    // DEBT-HOOK-PLANSTATUS-GATES-EVERY-COMMIT-001 — measured directly against the real `backlog`
    // CLI: a store that fails to OPEN (e.g. `ADHD_BACKLOG_DATABASE_PATH` pointed at a directory
    // instead of a file) does not make `query` exit non-zero or emit bad JSON — it exits 0 and
    // writes a well-formed JSON *error object* (`{"code":"internal","message":...}`) to stdout
    // instead of the expected `{ok,data:{items}}` envelope. That object is valid JSON, so the
    // JSON.parse guard above does not catch it — and it is exactly the D3 failure mode restated one
    // layer down: a non-envelope response would either throw a cryptic "items is not iterable"
    // TypeError (unrelated to the real cause) or, if `items` merely lacked `.length`, silently
    // page-loop forever. Treat any non-envelope response as store-unavailable, surfacing the CLI's
    // own error object if present.
    if (parsed?.ok !== true || !Array.isArray(parsed?.data?.items)) {
      throw new StoreUnavailableError(
        `plan-status: \`${BACKLOG_BIN} query\` (offset=${offset}) exited 0 but did not return a ` +
          `query envelope with data.items — got ${JSON.stringify(parsed).slice(0, 300)}. This is how ` +
          `the backlog CLI reports a store that failed to open (e.g. a corrupt or misdirected ` +
          `ADHD_BACKLOG_DATABASE_PATH) — treating it as store-unavailable rather than as "zero items".`,
      );
    }
    const items = parsed.data.items;
    for (const item of items) {
      // The graph's `title` field on migrated items still carries leftover embedded prose from the
      // original markdown import (e.g. "— **Open (LOW, feature)…**") — that is cosmetic import
      // residue, not the source of truth. `status` is authoritative; never parse `title` for it.
      const num = Number(String(item.humanId).replace(/^BL-/, ''));
      if (Number.isNaN(num)) continue;
      statuses.set(num, String(item.status ?? 'UNKNOWN').toUpperCase());
    }
    if (items.length < PAGE) break;
    offset += PAGE;
  }
  return statuses;
};

/**
 * [D1] Open-set, mapped from the graph's `status` enum. An id absent from the graph is treated as
 * closed (ABSENT) — matching the old markdown lifecycle where an id no longer present had been
 * archived. `UNKNOWN`/`MIXED`/`DEFERRED`/`PARTIAL`/`OUTSTANDING`/`IN_PROGRESS` are all OPEN:
 * conservative by design — an unverified or ambiguous state must never be silently counted as
 * closed (BL-225's exact failure mode, inverted). See SPEC-DELETE-FILES.md §D1 for the full table
 * and the ruled-out alternative.
 */
export const OPEN_STATUSES = new Set(['OPEN', 'IN_PROGRESS', 'PARTIAL', 'OUTSTANDING', 'DEFERRED', 'BLOCKED', 'MIXED', 'UNKNOWN']);
export const isOpen = (statuses, id) => OPEN_STATUSES.has(statuses.get(id) ?? 'ABSENT');

const readPackets = () => {
  const lines = readFileSync(PLAN, 'utf8').split('\n');
  const packets = [];
  let current = null;
  lines.forEach((line, i) => {
    const heading = line.match(/^### (PKT-\d+) — (.*)$/);
    if (heading) {
      current = {
        id: heading[1],
        num: Number(heading[1].slice(4)),
        title: heading[2],
        headingLine: i,
        targets: new Set(),
      };
      for (const ref of heading[2].match(/BL-\d+/g) ?? []) current.targets.add(Number(ref.slice(3)));
      packets.push(current);
      return;
    }
    if (current && /^\*\*Closes/.test(line)) {
      for (const ref of line.match(/BL-\d+/g) ?? []) current.targets.add(Number(ref.slice(3)));
    }
    // BL-435: the wave summary restates the tier distribution by hand. Compute it here so the
    // audit compares against a derived number rather than re-reading the file it is auditing.
    if (current && /^\*\*tier:\*\*/.test(line)) current.tier = line.match(/^\*\*tier:\*\*\s*(\w+)/)?.[1] ?? '?';
  });
  return packets;
};

const classify = (packet, statuses) => {
  const targets = [...packet.targets].sort((a, b) => a - b);
  const open = targets.filter((id) => isOpen(statuses, id));
  const status = targets.length === 0 ? 'NO-TARGET' : open.length === 0 ? 'DONE' : open.length === targets.length ? 'OPEN' : 'PARTIAL';
  return { ...packet, targets, open, status };
};

const build = () => {
  const statuses = readGraphStatuses();
  const packets = readPackets().map((p) => classify(p, statuses));
  const openIds = [...statuses.keys()].filter((id) => isOpen(statuses, id)).sort((a, b) => a - b);
  const targeted = new Set(packets.flatMap((p) => p.targets));
  const unscheduled = openIds.filter((id) => !targeted.has(id) && !OUT_OF_SCOPE.has(id));
  const outOfScopeOpen = openIds.filter((id) => OUT_OF_SCOPE.has(id));
  const staleRefs = [...targeted].filter((id) => !isOpen(statuses, id)).sort((a, b) => a - b);
  return { statuses, packets, openIds, unscheduled, outOfScopeOpen, staleRefs };
};

const bl = (ids) => (ids.length ? ids.map((i) => `BL-${i}`).join(', ') : '—');

const renderPlanBlock = (model) => {
  const { packets, openIds, unscheduled, outOfScopeOpen, staleRefs } = model;
  const counts = { DONE: 0, PARTIAL: 0, OPEN: 0, 'NO-TARGET': 0 };
  for (const p of packets) counts[p.status] += 1;
  const byNum = [...packets].sort((a, b) => a.num - b.num);

  const rows = byNum
    .map((p) => {
      const remaining = p.status === 'DONE' ? '—' : bl(p.open);
      return `| ${p.id} | **${p.status}** | ${bl(p.targets)} | ${remaining} |`;
    })
    .join('\n');

  return [
    BEGIN,
    GENERATED_NOTE,
    '',
    '### Packet ledger — derived from the backlog graph',
    '',
    'Regenerate with `node tools/plan-status.mjs`; `--check` fails if this block is stale.',
    'A packet is **DONE** only when every BL id it targets is closed — code landing is not enough',
    '(BL-225). Several packets below have merged code and still read OPEN; that is correct, and the',
    'remedy is to close the backlog item with a red→green test, not to edit this table.',
    '',
    `**${counts.DONE} done · ${counts.PARTIAL} partial · ${counts.OPEN} open** of ${packets.length} packets.`,
    '',
    `- Open backlog items in this program's scope: **${openIds.length - outOfScopeOpen.length}**, of which **${unscheduled.length}** have no packet.`,
    `- Open items deliberately out of scope: **${outOfScopeOpen.length}** — ${bl(outOfScopeOpen)}`,
    `- Unscheduled in-scope items (need a packet): ${bl(unscheduled)}`,
    `- Packet targets already closed (${staleRefs.length}) — historical context only, no work remains: ${bl(staleRefs)}`,
    '',
    '| Packet | Status | Targets | Still open |',
    '|---|---|---|---|',
    rows,
    '',
    END,
  ].join('\n');
};

const renderStateBlock = (model) => {
  const { packets, openIds, unscheduled, outOfScopeOpen } = model;
  const counts = { DONE: 0, PARTIAL: 0, OPEN: 0, 'NO-TARGET': 0 };
  for (const p of packets) counts[p.status] += 1;
  const inScope = openIds.length - outOfScopeOpen.length;
  const list = (status) =>
    packets
      .filter((p) => p.status === status)
      .sort((a, b) => a.num - b.num)
      .map((p) => p.id)
      .join(' ') || '—';

  return [
    BEGIN,
    GENERATED_NOTE,
    '',
    '## Progress — derived, not asserted',
    '',
    'Regenerate with `node tools/plan-status.mjs` (`--check` in a guard). The per-packet ledger lives',
    'in [`PLAN.md`](./PLAN.md); this is the summary.',
    '',
    '| | |',
    '|---|---|',
    `| Packets complete | **${counts.DONE} / ${packets.length}** |`,
    `| Packets partial | ${counts.PARTIAL} |`,
    `| Packets not started | ${counts.OPEN} |`,
    `| Open backlog items, in scope | **${inScope}** |`,
    `| Open backlog items, out of scope | ${outOfScopeOpen.length} |`,
    `| In-scope items with no packet | ${unscheduled.length}${unscheduled.length ? ` (${bl(unscheduled)})` : ''} |`,
    '',
    `**Done:** ${list('DONE')}`,
    '',
    `**Partial:** ${list('PARTIAL')}`,
    '',
    END,
  ].join('\n');
};

/**
 * A machine-owned status stamp. The suffix is the strongest "this line is generated and current"
 * signal the project has, so ANY line matching this inside a packet block is claimed by this tool.
 */
export const STAMP_RE = /^> \*\*status:/;

/** A packet block runs from its `### PKT-` heading to the next heading of any level. */
const isHeading = (line) => /^#{1,4} /.test(line ?? '');

export const renderStamp = (packet) => {
  const detail =
    packet.status === 'DONE'
      ? `all targets closed (${bl(packet.targets)})`
      : packet.status === 'NO-TARGET'
        ? 'no BL target parsed from this packet'
        : `still open: ${bl(packet.open)}`;
  return `> **status: ${packet.status}** — ${detail} · derived by \`tools/plan-status.mjs\`, do not hand-edit`;
};

/**
 * Stamp a machine-owned status line directly under each packet heading, and delete every OTHER
 * stamp in the same packet block.
 *
 * BL-464: this replacement used to be positional — it inspected only the line immediately after the
 * heading (optionally past one blank), so a second stamp deeper in a body was never rewritten, never
 * validated, and never reported by `--check`. Six packets carried one and four of them read `OPEN`
 * for shipped work, in the verbatim "derived … do not hand-edit" format. A duplicate is *stable*
 * rather than drifting, so it survived every regeneration indefinitely. The stamp is machine-owned
 * by declaration, so a second one is by definition garbage: drop it.
 */
export const stampPackets = (planSrc, model) => {
  const lines = planSrc.split('\n');
  const out = [];
  const byHeading = new Map(model.packets.map((p) => [p.headingLine, p]));
  let inPacket = false;
  for (let i = 0; i < lines.length; i += 1) {
    const packet = byHeading.get(i);
    if (packet) {
      inPacket = true;
      out.push(lines[i]);
      // Consume the heading's own blank lines and any stamp adjacent to it; the canonical
      // heading/blank/stamp/blank shape is re-emitted below, which keeps re-runs idempotent.
      let j = i + 1;
      while (j < lines.length && (lines[j] === '' || STAMP_RE.test(lines[j]))) j += 1;
      i = j - 1;
      out.push('', renderStamp(packet), '');
      continue;
    }
    if (isHeading(lines[i])) inPacket = false;
    if (inPacket && STAMP_RE.test(lines[i])) {
      // A second stamp deeper in the body. Drop it, and collapse the blank line it leaves behind
      // so removing it does not itself dirty the file on the next run.
      if (lines[i + 1] === '' && out[out.length - 1] === '') i += 1;
      continue;
    }
    out.push(lines[i]);
  }
  return out.join('\n');
};

/**
 * Slice out the regions opted in with AUDIT_MARKER. A region runs from the heading following the
 * marker to the next heading of the same or higher level, so a subsection stays inside its parent.
 */
export const auditedRegions = (src) => {
  const lines = src.split('\n');
  const regions = [];
  for (let i = 0; i < lines.length; i += 1) {
    if (lines[i].trim() !== AUDIT_MARKER) continue;
    let h = i + 1;
    while (h < lines.length && lines[h].trim() === '') h += 1;
    const heading = lines[h]?.match(/^(#{1,6}) (.*)$/);
    if (!heading) continue;
    const level = heading[1].length;
    let end = h + 1;
    while (end < lines.length) {
      const m = lines[end].match(/^(#{1,6}) /);
      if (m && m[1].length <= level) break;
      end += 1;
    }
    regions.push({ heading: `${heading[1]} ${heading[2]}`, startLine: h, lines: lines.slice(h + 1, end) });
  }
  return regions;
};

/**
 * Actionable lines in an audited region: not blockquotes (editorial/historical narrative), not
 * inside a fenced code block (the wave summary embeds a verification snippet full of `### PKT-`).
 */
const actionableLines = (lines) => {
  const out = [];
  let fenced = false;
  for (const line of lines) {
    if (/^\s*```/.test(line)) {
      fenced = !fenced;
      continue;
    }
    if (fenced || /^\s*>/.test(line)) continue;
    out.push(line);
  }
  return out;
};

/** Ids named inside a **bold** span — a to-do item's declared target, as opposed to a citation. */
const boldTokens = (lines) => {
  const found = [];
  for (const line of lines) {
    for (const b of line.matchAll(/\*\*(.+?)\*\*/g)) {
      for (const m of b[1].matchAll(/\b(BL|PKT)-(\d+)\b/g)) found.push({ kind: m[1], num: Number(m[2]), text: b[1] });
    }
  }
  return found;
};

/**
 * BL-435 — fail when hand-written actionable prose points at finished work, or restates a total the
 * tool already computes and gets it wrong.
 */
export const auditProse = (src, file, model) => {
  const violations = [];
  const regions = auditedRegions(src);

  for (const required of REQUIRED_AUDITED_SECTIONS[file] ?? []) {
    if (!regions.some((r) => r.heading.startsWith(required))) {
      violations.push(
        `${file}: section "${required}" is hand-written and must carry ${AUDIT_MARKER} directly above its heading — ` +
          `without it this section is outside every guard, which is BL-435 itself.`,
      );
    }
  }

  const doneByPacket = new Map(model.packets.map((p) => [p.id, p.status]));
  for (const region of regions) {
    const lines = actionableLines(region.lines);
    for (const token of boldTokens(lines)) {
      if (token.kind === 'BL') {
        if (!isOpen(model.statuses, token.num)) {
          violations.push(
            `${file} § ${region.heading}: names BL-${token.num} as an actionable target ("${token.text}"), but it is ` +
              `${model.statuses.get(token.num) ?? 'absent from the backlog graph, i.e. shipped'} — finished work.`,
          );
        }
      } else if (doneByPacket.get(`PKT-${token.num}`) === 'DONE') {
        violations.push(
          `${file} § ${region.heading}: names PKT-${token.num} as an actionable target ("${token.text}"), but every ` +
            `BL id it targets is closed — the packet is DONE.`,
        );
      }
    }

    // Totals the tool already computes. The wave summary restated these by hand and drifted two
    // whole waves before anyone noticed.
    const body = lines.join('\n');
    const total = body.match(/Total:\s*(\d+)\s*packets/i);
    if (total && Number(total[1]) !== model.packets.length) {
      violations.push(
        `${file} § ${region.heading}: states "Total: ${total[1]} packets"; the derived ledger has ${model.packets.length}.`,
      );
    }
    const tiers = {};
    for (const p of model.packets) tiers[p.tier ?? '?'] = (tiers[p.tier ?? '?'] ?? 0) + 1;
    for (const [tier, n] of Object.entries(tiers)) {
      const stated = body.match(new RegExp(`\\*\\*${tier}\\s+(\\d+)\\*\\*`, 'i'));
      if (stated && Number(stated[1]) !== n) {
        violations.push(
          `${file} § ${region.heading}: states ${tier} ${stated[1]}; recomputing the packets' \`tier:\` fields gives ${n}.`,
        );
      }
    }
  }
  return violations;
};

const replaceBlock = (src, block, file) => {
  const start = src.indexOf(BEGIN);
  const end = src.indexOf(END);
  if (start < 0 || end < 0) {
    throw new Error(`${file}: missing ${BEGIN} / ${END} markers — add them where the derived block belongs.`);
  }
  return src.slice(0, start) + block + src.slice(end + END.length);
};

const main = () => {
  const check = process.argv.includes('--check');
  const advisory = process.argv.includes('--advisory');

  let model;
  try {
    model = build();
  } catch (err) {
    if (!(err instanceof StoreUnavailableError)) throw err;
    // DEBT-HOOK-PLANSTATUS-GATES-EVERY-COMMIT-001: the store being unreachable is NOT drift, and
    // must be reported and exited distinctly from it (exit 2, never the drift exit 1) so a caller
    // can tell "the docs are stale" apart from "I couldn't check". `--advisory` additionally
    // downgrades this to exit 0 — the store's availability must never gate a normal commit.
    console.error(`plan-status: STORE UNAVAILABLE — ${err.message}`);
    if (advisory) {
      console.error(
        'plan-status: --advisory mode — NOT blocking this commit. Drift (if any) could not be checked ' +
          'because the backlog store was unreachable. This is a store-availability problem, not a ' +
          'plan-drift problem; the two used to be indistinguishable and a corrupted store once blocked ' +
          'every commit in the repo for that reason. Re-run `node tools/plan-status.mjs --check` once ' +
          'the store is back, or let CI catch genuine drift.',
      );
      process.exit(0);
    }
    process.exit(2);
  }

  if (process.argv.includes('--json')) {
    const { statuses, packets, ...rest } = model;
    console.log(JSON.stringify({ ...rest, packets: packets.map(({ headingLine, ...p }) => ({ ...p, targets: p.targets })) }, null, 2));
    return;
  }

  const planBefore = readFileSync(PLAN, 'utf8');
  const planAfter = replaceBlock(stampPackets(planBefore, model), renderPlanBlock(model), 'PLAN.md');
  const stateBefore = readFileSync(STATE, 'utf8');
  const stateAfter = replaceBlock(stateBefore, renderStateBlock(model), 'STATE.md');

  const stale = [];
  if (planAfter !== planBefore) stale.push('docs/reporting/memory/PLAN.md');
  if (stateAfter !== stateBefore) stale.push('docs/reporting/memory/STATE.md');

  // BL-435: the derived blocks can match the backlog graph perfectly while the hand-written sections a
  // reader actually starts from point at finished work. Audit those too, in both files.
  const violations = [...auditProse(planBefore, 'PLAN.md', model), ...auditProse(stateBefore, 'STATE.md', model)];

  if (check) {
    if (stale.length || violations.length) {
      if (stale.length) console.error(`plan-status: STALE — ${stale.join(', ')}. Run \`node tools/plan-status.mjs\`.`);
      for (const v of violations) console.error(`plan-status: STALE PROSE — ${v}`);
      if (violations.length) {
        console.error(
          `plan-status: ${violations.length} hand-written claim(s) name finished work or restate a derived total. ` +
            `These sections are not regenerated — edit the prose.`,
        );
      }
      // This IS genuine drift (the store was reachable and answered) — never conflate it with the
      // StoreUnavailableError branch above, which exits 2. Drift is exit 1.
      if (advisory) {
        console.error(
          'plan-status: --advisory mode — NOT blocking this commit, but the drift above is real and ' +
            'should be fixed (`node tools/plan-status.mjs`) or will be caught by the targeted blocking ' +
            'check that runs when PLAN.md/STATE.md are staged directly (see .husky/pre-commit).',
        );
        process.exit(0);
      }
      process.exit(1);
    }
    console.error('plan-status: OK — derived blocks match the backlog graph, audited prose names only open work.');
    return;
  }

  for (const v of violations) console.error(`plan-status: STALE PROSE — ${v}`);

  if (planAfter !== planBefore) writeFileSync(PLAN, planAfter);
  if (stateAfter !== stateBefore) writeFileSync(STATE, stateAfter);

  const counts = model.packets.reduce((a, p) => ({ ...a, [p.status]: (a[p.status] ?? 0) + 1 }), {});
  console.error(
    `plan-status: ${counts.DONE ?? 0} done / ${counts.PARTIAL ?? 0} partial / ${counts.OPEN ?? 0} open ` +
      `of ${model.packets.length} packets · ${model.unscheduled.length} in-scope item(s) with no packet` +
      (stale.length ? ` · updated ${stale.length} file(s)` : ' · already current'),
  );
};

// Only run when invoked as a script. Importing this module (the BL-464/BL-435 regression tests do)
// must never execute main(), which writes PLAN.md and STATE.md.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
