#!/usr/bin/env node
/**
 * plan-status.mjs — derive memory-program plan status from BACKLOG.md.
 *
 * WHY THIS EXISTS
 * ---------------
 * `docs/reporting/memory/PLAN.md` and `STATE.md` are supposed to be the source of truth for
 * "what is left". Between 2026-07-31 and 2026-08-03 both drifted badly while looking authoritative:
 * PLAN.md named 39 BL ids that had already closed, and STATE.md carried a prominent warning
 * ("62% of the backlog appears nowhere in the plan") that was true when written and false by the
 * time anyone read it. An agent following either document would have worked on finished items.
 *
 * That is the same failure mode BL-224 fixed for BACKLOG.md's own status header: a derived fact
 * maintained by hand. The fix is the same — derive it, and provide a --check mode so a stale
 * document fails a guard instead of quietly misleading the next reader.
 *
 * A packet's status is defined ENTIRELY by the backlog status of the BL ids it targets:
 *
 *   DONE     every target id is closed (RESOLVED/CLOSED, or archived out of BACKLOG.md entirely)
 *   PARTIAL  some targets closed, some still open
 *   OPEN     no target is closed
 *
 * This is deliberate and follows BL-225: a packet is done when its *backlog items* are verifiably
 * done, not when someone believes the code landed. Several packets (PKT-47, 48, 51, 53) have code
 * merged and still read OPEN here — correctly, because their acceptance was never fully met.
 * If you think a packet is done, close its BL item with a red->green test; do not edit this output.
 *
 * USAGE
 *   node tools/plan-status.mjs            # rewrite the derived blocks in PLAN.md and STATE.md
 *   node tools/plan-status.mjs --check    # exit 1 if either file is stale (for a pre-commit guard)
 *   node tools/plan-status.mjs --json     # emit the computed model, write nothing
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const BACKLOG = resolve(ROOT, 'BACKLOG.md');
const PLAN = resolve(ROOT, 'docs/reporting/memory/PLAN.md');
const STATE = resolve(ROOT, 'docs/reporting/memory/STATE.md');

const BEGIN = '<!-- PLAN-STATUS:BEGIN -->';
const END = '<!-- PLAN-STATUS:END -->';
const GENERATED_NOTE =
  '<!-- Generated by tools/plan-status.mjs from BACKLOG.md. Do not hand-edit — run the tool. -->';

/**
 * Items that are open in BACKLOG.md but deliberately outside this program's scope. Without this
 * list every unrelated repo defect (dispatch-optimizer, packaging, plan hygiene) shows up as an
 * unscheduled coverage gap, which is how the previous "62% uncovered" figure became alarming
 * noise rather than a signal. Keep this list short and justify each entry in PLAN.md's
 * "Explicitly OUT OF SCOPE" section — an id belongs here only if it is genuinely a different
 * project, never merely because it is inconvenient.
 */
const OUT_OF_SCOPE = new Set([
  // "Dispatch-optimizer / plan hygiene"
  99, 103, 104, 105, 228, 258, 261, 296, 298,
  // "Packaging, native ABI, bundling"
  282, 284, 285, 288, 291, 292, 305, 306, 308, 314, 333, 355, 408,
  // "Bundler / CI packaging"
  307, 309,
  // "Product surface"
  315,
  // "Open, but deliberately NO packet"
  225, 163, 283, 411,
]);

const readBacklogStatuses = () => {
  const src = readFileSync(BACKLOG, 'utf8');
  const statuses = new Map();
  const re = /^### BL-(\d+) — ([^\n]*)$/gm;
  let m;
  while ((m = re.exec(src)) !== null) {
    // A RESERVED heading is an id placeholder written by tools/allocate-bl-id.mjs, not a defect.
    // In a shared checkout several agents hold reservations in the worktree at once (8 were
    // outstanding on 2026-08-03). Counting them as open items reports them as "in-scope work with
    // no packet", which is a fabricated backlog — the exact kind of confidently-wrong derived
    // number this tool exists to prevent. They are skipped entirely; they can never be committed
    // anyway, since check-backlog-markers.mjs rejects them.
    if (/RESERVED/.test(m[2])) continue;
    const marker = m[2].match(/\*\*(REOPENED|BLOCKED|RESOLVED|CLOSED|Open|OPEN|WONTFIX)/i);
    statuses.set(Number(m[1]), marker ? marker[1].toUpperCase() : 'UNMARKED');
  }
  return statuses;
};

// An id absent from BACKLOG.md was resolved and archived to CHANGELOG.md — that is the documented
// lifecycle, so absence means closed, not unknown.
const isOpen = (statuses, id) => ['OPEN', 'REOPENED', 'BLOCKED'].includes(statuses.get(id) ?? 'ABSENT');

const readPackets = () => {
  const lines = readFileSync(PLAN, 'utf8').split('\n');
  const packets = [];
  let current = null;
  lines.forEach((line, i) => {
    const heading = line.match(/^### (PKT-\d+) — (.*)$/);
    if (heading) {
      current = {
        id: heading[1],
        num: Number(heading[1].slice(4)),
        title: heading[2],
        headingLine: i,
        targets: new Set(),
      };
      for (const ref of heading[2].match(/BL-\d+/g) ?? []) current.targets.add(Number(ref.slice(3)));
      packets.push(current);
      return;
    }
    if (current && /^\*\*Closes/.test(line)) {
      for (const ref of line.match(/BL-\d+/g) ?? []) current.targets.add(Number(ref.slice(3)));
    }
  });
  return packets;
};

const classify = (packet, statuses) => {
  const targets = [...packet.targets].sort((a, b) => a - b);
  const open = targets.filter((id) => isOpen(statuses, id));
  const status = targets.length === 0 ? 'NO-TARGET' : open.length === 0 ? 'DONE' : open.length === targets.length ? 'OPEN' : 'PARTIAL';
  return { ...packet, targets, open, status };
};

const build = () => {
  const statuses = readBacklogStatuses();
  const packets = readPackets().map((p) => classify(p, statuses));
  const openIds = [...statuses.keys()].filter((id) => isOpen(statuses, id)).sort((a, b) => a - b);
  const targeted = new Set(packets.flatMap((p) => p.targets));
  const unscheduled = openIds.filter((id) => !targeted.has(id) && !OUT_OF_SCOPE.has(id));
  const outOfScopeOpen = openIds.filter((id) => OUT_OF_SCOPE.has(id));
  const staleRefs = [...targeted].filter((id) => !isOpen(statuses, id)).sort((a, b) => a - b);
  return { statuses, packets, openIds, unscheduled, outOfScopeOpen, staleRefs };
};

const bl = (ids) => (ids.length ? ids.map((i) => `BL-${i}`).join(', ') : '—');

const renderPlanBlock = (model) => {
  const { packets, openIds, unscheduled, outOfScopeOpen, staleRefs } = model;
  const counts = { DONE: 0, PARTIAL: 0, OPEN: 0, 'NO-TARGET': 0 };
  for (const p of packets) counts[p.status] += 1;
  const byNum = [...packets].sort((a, b) => a.num - b.num);

  const rows = byNum
    .map((p) => {
      const remaining = p.status === 'DONE' ? '—' : bl(p.open);
      return `| ${p.id} | **${p.status}** | ${bl(p.targets)} | ${remaining} |`;
    })
    .join('\n');

  return [
    BEGIN,
    GENERATED_NOTE,
    '',
    '### Packet ledger — derived from `BACKLOG.md`',
    '',
    'Regenerate with `node tools/plan-status.mjs`; `--check` fails if this block is stale.',
    'A packet is **DONE** only when every BL id it targets is closed — code landing is not enough',
    '(BL-225). Several packets below have merged code and still read OPEN; that is correct, and the',
    'remedy is to close the backlog item with a red→green test, not to edit this table.',
    '',
    `**${counts.DONE} done · ${counts.PARTIAL} partial · ${counts.OPEN} open** of ${packets.length} packets.`,
    '',
    `- Open backlog items in this program's scope: **${openIds.length - outOfScopeOpen.length}**, of which **${unscheduled.length}** have no packet.`,
    `- Open items deliberately out of scope: **${outOfScopeOpen.length}** — ${bl(outOfScopeOpen)}`,
    `- Unscheduled in-scope items (need a packet): ${bl(unscheduled)}`,
    `- Packet targets already closed (${staleRefs.length}) — historical context only, no work remains: ${bl(staleRefs)}`,
    '',
    '| Packet | Status | Targets | Still open |',
    '|---|---|---|---|',
    rows,
    '',
    END,
  ].join('\n');
};

const renderStateBlock = (model) => {
  const { packets, openIds, unscheduled, outOfScopeOpen } = model;
  const counts = { DONE: 0, PARTIAL: 0, OPEN: 0, 'NO-TARGET': 0 };
  for (const p of packets) counts[p.status] += 1;
  const inScope = openIds.length - outOfScopeOpen.length;
  const list = (status) =>
    packets
      .filter((p) => p.status === status)
      .sort((a, b) => a.num - b.num)
      .map((p) => p.id)
      .join(' ') || '—';

  return [
    BEGIN,
    GENERATED_NOTE,
    '',
    '## Progress — derived, not asserted',
    '',
    'Regenerate with `node tools/plan-status.mjs` (`--check` in a guard). The per-packet ledger lives',
    'in [`PLAN.md`](./PLAN.md); this is the summary.',
    '',
    '| | |',
    '|---|---|',
    `| Packets complete | **${counts.DONE} / ${packets.length}** |`,
    `| Packets partial | ${counts.PARTIAL} |`,
    `| Packets not started | ${counts.OPEN} |`,
    `| Open backlog items, in scope | **${inScope}** |`,
    `| Open backlog items, out of scope | ${outOfScopeOpen.length} |`,
    `| In-scope items with no packet | ${unscheduled.length}${unscheduled.length ? ` (${bl(unscheduled)})` : ''} |`,
    '',
    `**Done:** ${list('DONE')}`,
    '',
    `**Partial:** ${list('PARTIAL')}`,
    '',
    END,
  ].join('\n');
};

/**
 * A machine-owned status stamp. The suffix is the strongest "this line is generated and current"
 * signal the project has, so ANY line matching this inside a packet block is claimed by this tool.
 */
export const STAMP_RE = /^> \*\*status:/;

/** A packet block runs from its `### PKT-` heading to the next heading of any level. */
const isHeading = (line) => /^#{1,4} /.test(line ?? '');

export const renderStamp = (packet) => {
  const detail =
    packet.status === 'DONE'
      ? `all targets closed (${bl(packet.targets)})`
      : packet.status === 'NO-TARGET'
        ? 'no BL target parsed from this packet'
        : `still open: ${bl(packet.open)}`;
  return `> **status: ${packet.status}** — ${detail} · derived by \`tools/plan-status.mjs\`, do not hand-edit`;
};

/**
 * Stamp a machine-owned status line directly under each packet heading, and delete every OTHER
 * stamp in the same packet block.
 *
 * BL-464: this replacement used to be positional — it inspected only the line immediately after the
 * heading (optionally past one blank), so a second stamp deeper in a body was never rewritten, never
 * validated, and never reported by `--check`. Six packets carried one and four of them read `OPEN`
 * for shipped work, in the verbatim "derived … do not hand-edit" format. A duplicate is *stable*
 * rather than drifting, so it survived every regeneration indefinitely. The stamp is machine-owned
 * by declaration, so a second one is by definition garbage: drop it.
 */
export const stampPackets = (planSrc, model) => {
  const lines = planSrc.split('\n');
  const out = [];
  const byHeading = new Map(model.packets.map((p) => [p.headingLine, p]));
  let inPacket = false;
  for (let i = 0; i < lines.length; i += 1) {
    const packet = byHeading.get(i);
    if (packet) {
      inPacket = true;
      out.push(lines[i]);
      // Consume the heading's own blank lines and any stamp adjacent to it; the canonical
      // heading/blank/stamp/blank shape is re-emitted below, which keeps re-runs idempotent.
      let j = i + 1;
      while (j < lines.length && (lines[j] === '' || STAMP_RE.test(lines[j]))) j += 1;
      i = j - 1;
      out.push('', renderStamp(packet), '');
      continue;
    }
    if (isHeading(lines[i])) inPacket = false;
    if (inPacket && STAMP_RE.test(lines[i])) {
      // A second stamp deeper in the body. Drop it, and collapse the blank line it leaves behind
      // so removing it does not itself dirty the file on the next run.
      if (lines[i + 1] === '' && out[out.length - 1] === '') i += 1;
      continue;
    }
    out.push(lines[i]);
  }
  return out.join('\n');
};

const replaceBlock = (src, block, file) => {
  const start = src.indexOf(BEGIN);
  const end = src.indexOf(END);
  if (start < 0 || end < 0) {
    throw new Error(`${file}: missing ${BEGIN} / ${END} markers — add them where the derived block belongs.`);
  }
  return src.slice(0, start) + block + src.slice(end + END.length);
};

const main = () => {
  const check = process.argv.includes('--check');
  const model = build();

  if (process.argv.includes('--json')) {
    const { statuses, packets, ...rest } = model;
    console.log(JSON.stringify({ ...rest, packets: packets.map(({ headingLine, ...p }) => ({ ...p, targets: p.targets })) }, null, 2));
    return;
  }

  const planBefore = readFileSync(PLAN, 'utf8');
  const planAfter = replaceBlock(stampPackets(planBefore, model), renderPlanBlock(model), 'PLAN.md');
  const stateBefore = readFileSync(STATE, 'utf8');
  const stateAfter = replaceBlock(stateBefore, renderStateBlock(model), 'STATE.md');

  const stale = [];
  if (planAfter !== planBefore) stale.push('docs/reporting/memory/PLAN.md');
  if (stateAfter !== stateBefore) stale.push('docs/reporting/memory/STATE.md');

  if (check) {
    if (stale.length) {
      console.error(`plan-status: STALE — ${stale.join(', ')}. Run \`node tools/plan-status.mjs\`.`);
      process.exit(1);
    }
    console.error('plan-status: OK — derived blocks match BACKLOG.md.');
    return;
  }

  if (planAfter !== planBefore) writeFileSync(PLAN, planAfter);
  if (stateAfter !== stateBefore) writeFileSync(STATE, stateAfter);

  const counts = model.packets.reduce((a, p) => ({ ...a, [p.status]: (a[p.status] ?? 0) + 1 }), {});
  console.error(
    `plan-status: ${counts.DONE ?? 0} done / ${counts.PARTIAL ?? 0} partial / ${counts.OPEN ?? 0} open ` +
      `of ${model.packets.length} packets · ${model.unscheduled.length} in-scope item(s) with no packet` +
      (stale.length ? ` · updated ${stale.length} file(s)` : ' · already current'),
  );
};

// Only run when invoked as a script. Importing this module (the BL-464/BL-435 regression tests do)
// must never execute main(), which writes PLAN.md and STATE.md.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
