/**
 * BL-507 — the Drizzle-era explicit-rowid FK form (`REFERENCES node(rowid)`)
 * on `edge` breaks every write on Turso when `foreign_keys=ON`; `applySchema`
 * must self-heal it by rebuilding `edge` with the canonical implicit form.
 *
 * ## Root cause (measured in .worktrees/c-fix-fts, 2026-08-11)
 *
 * Pre-graph-store stores (the live backlog.db is one) were generated by
 * drizzle-orm and carry `src INTEGER NOT NULL REFERENCES node(rowid)`. On
 * stock SQLite that resolves (rowid is the INTEGER PRIMARY KEY alias); on
 * Turso/libSQL with `PRAGMA foreign_keys = ON` it does NOT — every statement
 * that triggers FK validation dies with `Runtime error: foreign key mismatch
 * referencing "node"` (reproduced on a copy of the live store; also the exact
 * error the backlog CLI itself throws today). The implicit form
 * (`REFERENCES node ON DELETE CASCADE`, what graph-store emits) resolves on
 * BOTH engines.
 *
 * The fix extends the existing self-heal in `ensureCheckConstraints` (the
 * same rebuild machinery as the enum-check normalization): an `edge` whose
 * DDL carries an explicit `REFERENCES ...(rowid)` FK is rebuilt with
 * `EDGE_TABLE_DDL` at open (ADR-0007 self-healing).
 *
 * ## RED→GREEN (BL-225)
 *
 * RED (current code): a store carrying the live-shaped edge DDL opens and
 * `writeNode` fails with the FK-mismatch error. GREEN (fix): `applySchema`
 * rebuilds `edge`, writes succeed, and the stored DDL is normalized.
 *
 * Both engine arms use real adapters (real better-sqlite3, real
 * @tursodatabase/database) — no mocks, no env gates.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { SqliteAdapterImpl, TursoAdapterImpl } from '@adhd/sox-store-adapter';
import type { StoreAdapter } from '@adhd/sox-store-adapter';
import { createGraphBackend } from './index.js';

const hasTurso = (() => {
  try {
    require.resolve('@tursodatabase/database');
    return true;
  } catch {
    return false;
  }
})();

/** The live backlog.db's node DDL (Drizzle-era, backtick-quoted, enum CHECKs). */
const LIVE_NODE_DDL = `CREATE TABLE \`node\` (
  \`rowid\` integer PRIMARY KEY NOT NULL,
  \`uid\` text NOT NULL,
  \`kind\` text NOT NULL CHECK (\`kind\` IN ('episode','entity','claim','community','session','generic')),
  \`content\` text, \`name\` text, \`summary\` text, \`topic\` text, \`tags\` text,
  \`importance\` real DEFAULT 1.0, \`confidence\` real, \`content_hash\` text,
  \`namespace\` text DEFAULT 'global', \`meta\` text, \`agent_id\` text, \`session_id\` text,
  \`source\` text CHECK (\`source\` IN ('message','tool_output','observation','document','reflection','import')),
  \`project_path\` text, \`level\` integer, \`resume_state\` text, \`t_occurred\` text, \`t_expires\` text,
  \`t_created\` text NOT NULL, \`t_valid\` text, \`t_invalid\` text, \`is_superseded\` integer DEFAULT 0,
  \`access_count\` integer DEFAULT 0, \`last_access\` text, \`t_updated\` text
)`;

/** The live backlog.db's edge DDL — the explicit-rowid FK form that breaks
 *  Turso writes under foreign_keys=ON. */
const LIVE_EDGE_DDL_EXPLICIT_ROWID = `CREATE TABLE \`edge\` (
  \`rowid\` integer PRIMARY KEY NOT NULL,
  \`src\` integer NOT NULL REFERENCES \`node\`(\`rowid\`) ON DELETE CASCADE,
  \`dst\` integer NOT NULL REFERENCES \`node\`(\`rowid\`) ON DELETE CASCADE,
  \`rel\` text NOT NULL CHECK (\`rel\` IN ('MENTIONS','SUPPORTS','RELATES_TO','SUPERSEDES','DERIVED_FROM','MEMBER_OF','PART_OF','SAME_AS','ASSIGNED_TO','DEPENDS_ON')),
  \`weight\` real DEFAULT 1.0, \`confidence\` real,
  \`origin\` text CHECK (\`origin\` IN ('extracted','inferred','user_asserted')),
  \`meta\` text, \`t_created\` text NOT NULL, \`t_expired\` text, \`t_valid\` text, \`t_invalid\` text
)`;

/** Seed the live-shaped node + edge DDL (explicit-rowid FK form) into a fresh
 *  store, then open it through the graph backend exactly as a consumer would. */
async function openLiveShapedStore(
  makeAdapter: (dbPath: string) => Promise<StoreAdapter>,
  dbPath: string,
): Promise<StoreAdapter> {
  const adapter = await makeAdapter(dbPath);
  await adapter.exec(LIVE_NODE_DDL);
  await adapter.exec(LIVE_EDGE_DDL_EXPLICIT_ROWID);
  return adapter;
}

let tmpDir: string;
beforeAll(() => {
  tmpDir = mkdtempSync(join(tmpdir(), 'graph-store-bl507-'));
});
afterAll(() => {
  rmSync(tmpDir, { recursive: true, force: true });
});

const tursoArm = hasTurso ? it : it.skip;

describe('BL-507 — explicit-rowid FK self-heal at applySchema (edge rebuild)', () => {
  tursoArm('turso: a live-shaped store heals at open; writeNode/writeEdge succeed; edge DDL normalized', async () => {
    const dbPath = join(tmpDir, `fk-turso-${Date.now()}-${Math.random().toString(36).slice(2, 8)}.db`);
    const adapter = await openLiveShapedStore((p) => TursoAdapterImpl.connect({ dbPath: p }), dbPath);
    try {
      const graph = createGraphBackend(adapter);
      // RED (current code): writeNode fails with `foreign key mismatch
      // referencing "node"` — the live production outage. GREEN (fix): the
      // edge rebuild at applySchema has normalized the FK first.
      await graph.applySchema();
      const id = await graph.writeNode('bl507 fk heal probe', {});
      expect(id).toBeGreaterThan(0);
      const id2 = await graph.writeNode('bl507 second node', {});
      await graph.writeEdge(id, id2, 'RELATES_TO', {});
      // The stored edge DDL must no longer carry the explicit rowid FK form.
      const edgeRow = await adapter.executeGet<{ sql: string }>(
        `SELECT sql FROM sqlite_master WHERE type='table' AND name='edge'`,
      );
      expect(edgeRow?.sql ?? '').not.toMatch(/references\s+`?node`?\s*\(\s*`?rowid`?\s*\)/i);
    } finally {
      await adapter.close();
    }
  }, 30000);

  it('sqlite: a live-shaped store keeps its identity byte-identical (BL-448 AC-3) and writes still work — stock SQLite resolves the explicit-rowid form', async () => {
    const dbPath = join(tmpDir, `fk-sqlite-${Date.now()}-${Math.random().toString(36).slice(2, 8)}.db`);
    const adapter = await openLiveShapedStore(async (p) => new SqliteAdapterImpl(p), dbPath);
    try {
      const graph = createGraphBackend(adapter);
      await graph.applySchema();
      const id = await graph.writeNode('bl507 sqlite heal probe', {});
      expect(id).toBeGreaterThan(0);
      const id2 = await graph.writeNode('bl507 sqlite second node', {});
      await graph.writeEdge(id, id2, 'RELATES_TO', {});
      // The BL-507 rebuild is turso-only (the form is only broken there);
      // on sqlite the store must keep its identity unchanged — the exact
      // BL-448 AC-3 contract: applySchema never churns a store that works.
      const edgeRow = await adapter.executeGet<{ sql: string }>(
        `SELECT sql FROM sqlite_master WHERE type='table' AND name='edge'`,
      );
      expect(edgeRow?.sql ?? '').toMatch(/references\s+`?node`?\s*\(\s*`?rowid`?\s*\)/i);
    } finally {
      await adapter.close();
    }
  }, 30000);
});
